# Generated by Django 4.0.4 on 2022-05-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('rating', models.SmallIntegerField()),
                ('authors', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('review', models.TextField()),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
